FROM node:20-alpine as build
WORKDIR /app

COPY package*.json ./

RUN npm install -g npm@11.6.0

RUN npm install

COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build


FROM nginx:alpine

RUN apk update && apk add --no-cache certbot certbot-nginx bash

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
