spring:
  application:
    name: confirmacao-presenca-api

  datasource:
    url: jdbc:postgresql://postgres:5432/eventos-db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    change-log: classpath:database/master.xml
    url: jdbc:postgresql://postgres:5432/eventos-db?createDatabaseIfNotExist=true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_APP}
    password: ${SENHA_APP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

cors:
  allowed-origins: "https://eventops.com.br,https://www.eventops.com.br"

app:
  frontend-url: https://eventops.com.br
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-ms: 1800000

server:
  port: 8080